### ISSUE TITLE
Missing nuget package

### ISSUE THREAD

**Issue by mohaaron** [jsakamoto/Toolbelt.Blazor.HotKeys2#1]
Are you aware that there is no Nuget package to use for installing?

**Comment by jsakamoto** [comment]
@mohaaron Sorry for bothering you. Actually, this project is still in progress!
I'm going to make this project to be completed and release it as a NuGet package as soon as possible.

**Comment by jsakamoto** [comment]
@mohaaron The NuGet package of the Blazor HotKeys2 has been published 3 months ago. Thanks.
