### ISSUE TITLE
Could not find 'Toolbelt.Blazor.getProperty' ('getProperty' was undefined) on Blazor Web App Server Mode .NET8

### ISSUE THREAD

**Issue by detriv** [jsakamoto/Toolbelt.Blazor.HotKeys2#14]
I experienced this issue, when implementing it into my projects with framework.net Blazor web app, is there a solution for this, thank you
![Screenshot 2023-12-12 154512](https://github.com/jsakamoto/Toolbelt.Blazor.HotKeys2/assets/38879571/ca3d1367-44e8-44f0-8c9c-44866b9786b9)

**Comment by jsakamoto** [comment]
@devatrivanus18 Thank you for your report!

Could you tell me which version of the "Toolbelt.Blazor.HotKeys2" NuGet package you are using? And I'd appreciate it if you could attach the minimal sample code that can reproduce the issue.

**Comment by jsakamoto** [comment]
@devatrivanus18 Could you try the latest version, ver.3.2.1, of the "Blazor HotKeys2" out?

- https://www.nuget.org/packages/Toolbelt.Blazor.HotKeys2/3.2.1

**Comment by detriv** [comment]
I've tried this version ver.3.2.1, yesterday's issue has already appeared, Thanks
