### ISSUE TITLE
Disposing immediately after "CreateContext" will not work.

### ISSUE THREAD

**Issue by TFujisawa123** [jsakamoto/Toolbelt.Blazor.HotKeys2#20]
The code below does not dispose "HotKeysContext".
Even after Dispose, the "G" key hotkey remains valid and cannot be deleted.

```csharp
this.HotKeysContext = this.HotKeys.CreateContext().Add(Code.G, OnHotKey);
for (int i = 0; i < 100; i++)
{
    // something process
}
this.HotKeysContext?.Dispose();
```

Inserting "Task.Delay(1)" will dispose successfully.
```csharp
this.HotKeysContext = this.HotKeys.CreateContext().Add(Code.G, OnHotKey);
for (int i = 0; i < 100; i++)
{
    // something process
}
await Task.Delay(1);
this.HotKeysContext?.Dispose();
```

**Comment by jsakamoto** [comment]
Hello @TFujisawa123,
Thank you for letting me know that bug! I fixed it and published a new version today.

- https://www.nuget.org/packages/Toolbelt.Blazor.HotKeys2/4.0.1#releasenotes-body-tab

Could you try it out? Again, thank you for your contributions!

**Comment by TFujisawa123** [comment]
Thanks that update. It worked as expected.
