### ISSUE TITLE
Add Code "NumpadEnter"

### ISSUE THREAD

**Issue by holotrek** [jsakamoto/Toolbelt.Blazor.HotKeys2#26]
NumpadEnter is a different Code than Enter and sometimes we may want to react differently to it. Current workaround is just to use `new Code("NumpadEnter")` but it seems like it would be easy enough to add this code.

Key.Enter includes both enter keys, but there is no ModKey.Shift when you want to check if the shift key was included with the Numpad Enter key.

**Comment by jsakamoto** [comment]
Hi @holotrek, thank you for your reporting.

I've released the improved version, the "Blazor HotKeys2" ver 5.1.0, today. I've added new predefined keys and codes, such as `NumpadEnter`. Please check it out.

Again, thank you for your contributions!
