### ISSUE TITLE
Exclude does not work with Blazor FluentUI

### ISSUE THREAD

**Issue by GeorgeF0** [jsakamoto/Toolbelt.Blazor.HotKeys2#28]
Hi! I'm not sure if i should be posting this here or in another repo, but it seems that Blazor FluentUI text inputs do not work with this library.

More specifically the "exclude" settings are not honored when a FluentUI component is in focus.

I think the reason for this is that `isExcludeTarget` in `script.js` doesn't see the underlying input component. 

Here I have a FluentUI text field next to a regular text field:
![tmp_df1a4eb2-fe69-4e07-b15e-caf2139cbde3](https://github.com/user-attachments/assets/22a6a7b0-8a71-4b51-aad1-6e508904522a)

They look like this:
![tmp_b742a076-6739-4a14-8db1-b5f4a6786984](https://github.com/user-attachments/assets/1b31b195-e5a6-4675-89d8-9c0a89c8a647)

When i put a breakpoint in your (minified) script so I can inspect `isExcludeTarget`, the captured `targetElement` is not the input element, but rather some wrapper element that has the input element in its `proxy` field, and the `tagName` is not `INPUT` but rather `FLUENT-TEXT-FIELD`:
![tmp_6107a60c-480a-46f3-ba0a-be5ac8b36e49](https://github.com/user-attachments/assets/785f7048-3baf-49f7-b9b7-e28e8a8eb463)
![tmp_aab00c60-2382-40a6-bd82-27186e295fd6](https://github.com/user-attachments/assets/1bc35712-16dd-405d-9543-d475f380fbb9)

Would it be possible to add support for FluentUI to this library? Thanks!

**Comment by jsakamoto** [comment]
@GeorgeF0 Thank you for letting me know about the problem. I'll investigate it, but it will take a long time to create a Blazor application project that can reproduce it. I'd appreciate it if you could provide me with a minimal sample project to produce the problem you reported.
Of course, I will fix this issue eventually, even if you cannot provide a sample project.

Unfortunately, I'm really busy writing technical blog posts this month, December. So please give me time. Thank you for your understanding.

**Comment by GeorgeF0** [comment]
Hi! Thank you very much for the quick reply. 

I had a bit of free time so I prepared a sample project to illustrate the issue. I forked your project [here](https://github.com/GeorgeF0/Toolbelt.Blazor.HotKeys2) and added 3 branches:
- [feature/blazor-fluent-ui-sample](https://github.com/GeorgeF0/Toolbelt.Blazor.HotKeys2/tree/feature/blazor-fluent-ui-sample): this branch adds a Blazor + Fluent UI project. It has a page that allows you to test a shortcut with regular input elements and Fluent UI elements so you can see the difference in behavior
![image](https://github.com/user-attachments/assets/8d26f885-74c7-4cd8-b371-cbad6bde203c)
- [feature/blazor-fluent-ui-fix](https://github.com/GeorgeF0/Toolbelt.Blazor.HotKeys2/tree/feature/blazor-fluent-ui-fix): this is based on the top branch, but it then attempts to add support for Fluent UI components by amending `script.ts` to look for Fluent UI components. It only currently handles inputs and text areas.
- [feature/blazor-fluent-ui-manual](https://github.com/GeorgeF0/Toolbelt.Blazor.HotKeys2/tree/feature/blazor-fluent-ui-manual): this is also based on the top branch, and it attempts to solve the issue outside of the library. While inspecting the code I realized the library has an option to exclude elements based on matching CSS selectors. So by listing FluentUI components as a selector, it seems to be possible to solve the issue without having to change the library!

I appreciate you are busy this month, so let me know what you think when you have the time! In the meantime, I can use the `ExcludeSelector` trick! :)

**Comment by jsakamoto** [comment]
Hi @GeorgeF0, 
Thank you for providing a good sample. It's really helpful for me. I'm investigating it for now. What I've understood so far is that the root cause of this issue is that the hotkeys library can't identify the "keydown" event source (event target) element appropriately when the event source element is under a shadowDOM tree. I feel I'm close to a solution. Please give me a moment.

**Comment by jsakamoto** [comment]
Hi @GeorgeF0,
Thanks for your patience. I have finally fixed this issue and released a new version, v.6.0.

- https://www.nuget.org/packages/Toolbelt.Blazor.HotKeys2/6.0.0#releasenotes-body-tab

Please try it out. Again, thank you for your contributions!

P.S. Please remember that Fluent UI's checkbox consists only of div and SVG elements. It doesn't include any input elements, so you still need to describe the exclude selector, "fluent-checkbox," explicitly.

**Comment by GeorgeF0** [comment]
Hi @jsakamoto,

I've tried it just now and it works perfectly! Interesting solution - today I learned something new :) 
Thank you for all the help.
